version: '2'

services:

  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: beachtent
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  
  postgres:
    mem_limit: 1Gb
    image: 'postgres:9.5'
    volumes_from:
      - data_database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: beachtent
      POSTGRES_PASSWORD: beachtent

  redis:
    mem_limit: 1Gb
    image: redis:3-alpine
    command: redis-server --appendonly no
    hostname: redis
    ports:
      - "6379:6379"
    volumes_from:
      - data_redis

  data_redis:
    image: cogniteev/echo
    command: echo 'Data Container for Redis'
    volumes:
      - /data

  data_database:
    image: cogniteev/echo
    command: echo 'Data Container for Postgres'
    volumes:
      - /var/lib/postgresql/data
